"""Campo senha adicionado

Revision ID: b7774007f0b3
Revises: d5a7ca2fabfc
Create Date: 2025-11-08 20:39:03.928398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7774007f0b3'
down_revision: Union[str, Sequence[str], None] = 'd5a7ca2fabfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###
