"""Removendo senha

Revision ID: d5a7ca2fabfc
Revises: 67a233dae5f4
Create Date: 2025-11-08 20:36:12.492079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7ca2fabfc'
down_revision: Union[str, Sequence[str], None] = '67a233dae5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
